steps:
  # install nodejs
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: Install Node.js

  # run npm install
  - script: |
      npm ci
    displayName: 'Install dependencies'

  # for what?
  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
