trigger: none

pr:
- main
- develop

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
  - ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
    - template: common/sdl_steps.yml
  - template: common/setup_steps.yml
  - template: common/compile_steps.yml
  - template: common/test_steps.yml
