schedules:
- cron: '0 19 * * *'
  displayName: Nightly build on 3:00 AM (GMT+8)
  branches:
    include:
    - develop
  always: false

trigger: none
pr: none

stages:
- stage: test
  jobs:
  - job: test
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macos-latest'
        windows:
          imageName: 'windows-latest'
    pool:
      vmImage: $(imageName)
    steps:
      - template: common/setup_steps.yml
      - template: common/compile_steps.yml
      - template: common/check_steps.yml
      - template: common/test_steps.yml